baseURL = 'https://hexed-workshop.github.io/'
languageCode = 'en-us'
title = 'HEXED Workshop'
theme = "hugo-theme-monochrome"

[params]
footer = 'Copyright © 2025'
enable_toc = false


[[menu.navbar]]
identifier = "home"
name = "Home"
url = "/"
weight = 1

[[menu.navbar]]
identifier = "call-for-papers"
name = "Call for papers"
url = "/call-for-papers/"
weight = 2

[[menu.navbar]]
identifier = "review-guidelines"
name = "Review guidelines"
url = "/review-guidelines/"
weight = 3

[[menu.navbar]]
identifier = "schedule"
name = "Schedule"
url = "/schedule/"
weight = 4

[[menu.navbar]]
identifier = "proceedings"
name = "Proceedings"
url = "/proceedings/"
weight = 5

[[menu.navbar]]
identifier = "people"
name = "People"
url = "/people/"
weight = 6

[[menu.navbar]]
identifier = "previous-workshops"
name = "Previous workshops"
url = "/previous/"
weight = 7

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
